* Houdini C++ Wrangle 

  This Houdini node allows you to write wrangle nodes in C++ instead of VEX.

  VEX is an amazing tool for prototyping and fast production, however it is quite simplistic and sometimes broken language. Writing wrangle nodes in C++ brings the full expressive power of C++ and access to HDK(Houdini C++ API) in the expense of slow compilation times compared to VEX. 

  To make the transition from VEX to C++ as simple as possible, we provide C++ implementation of VEX functions. Therefore you can write almost the same code in C++ as you would write it with VEX.


** Original idea

   This node is an extension of the node made by [[https://vimeo.com/171189268][animatrix]]. My version should be easier to use for people experienced with VEX.

* Installation and Requirements

  Talk about how to modify `hcustom` to C++17 and add no warning flags.

  Tested only on Houdini 17 and g++ 8.1
 
* Three Modules

** cppvex
   C++ impelementation of VEX functions
** hougen
   connection between Houdini and Eigen
** fe
   finite element library
